=== Gulaev/Lawyers_Office/src/main/resources/xml_db/xsd/bankCard.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="bankCards">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="bankCard" type="bankCardType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:complexType name="bankCardType">
    <xs:sequence>
      <xs:element name="bankCardId" type="xs:int"/>
      <xs:element name="cardNumber" type="xs:string"/>
      <xs:element name="dateEnd" type="xs:date"/>
      <xs:element name="cvv" type="xs:int"/>
      <xs:element name="nameOnCard" type="xs:string"/>
      <xs:element name="clientId" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Gulaev/Lawyers_Office/src/main/resources/xml_db/bankCard.xml
<?xml version="1.0" encoding="UTF-8"?>
<bankCards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="xsd/bankCard.xsd">
  <bankCard>
    <bankCardId>1</bankCardId>
    <cardNumber>4567 4567 3234 2342</cardNumber>
    <dateEnd>2023-12-31</dateEnd>
    <cvv>123</cvv>
    <nameOnCard>John Doe</nameOnCard>
    <clientId>1</clientId>
  </bankCard>
  <bankCard>
    <bankCardId>2</bankCardId>
    <cardNumber>4537 4567 3234 2342</cardNumber>
    <dateEnd>2023-12-30</dateEnd>
    <cvv>233</cvv>
    <nameOnCard>John Jones</nameOnCard>
    <clientId>1</clientId>
  </bankCard>
</bankCards>
