=== Gulaev/Lawyers_Office/src/main/resources/xml_db/xsd/client.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="clients">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="client" type="clientType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

<!--    <xs:complexType  name="passportType">-->
<!--      <xs:sequence>-->
<!--        <xs:element name="passportId" type="xs:int"/>-->
<!--        <xs:element name="tin" type="xs:string"/>-->
<!--        <xs:element name="dateOfIssue" type="xs:date"/>-->
<!--        <xs:element name="issuedBy" type="xs:string"/>-->
<!--      </xs:sequence>-->
<!--    </xs:complexType>-->

  <xs:complexType name="clientType">
    <xs:sequence>
      <xs:element name="clientId" type="xs:int"/>
      <xs:element name="firstName" type="xs:string"/>
      <xs:element name="lastName" type="xs:string"/>
      <xs:element name="passportId" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Gulaev/Lawyers_Office/src/main/resources/xml_db/client.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="xsd/client.xsd">
  <client>
    <clientId>1</clientId>
    <firstName>Jane</firstName>
    <lastName>Doe</lastName>
    <passportId>1</passportId>
  </client>
  <client>
    <clientId>1</clientId>
    <firstName>Jone</firstName>
    <lastName>Hall</lastName>
    <passportId>2</passportId>
  </client>
</clients>
