=== Gulaev/Lawyers_Office/src/main/resources/xml_db/xsd/payment.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="payments">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="payment" type="paymentType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:complexType name="paymentType">
    <xs:sequence>
      <xs:element name="paymentId" type="xs:int"/>
      <xs:element name="dateOfPayment" type="xs:date"/>
      <xs:element name="clientId" type="xs:int"/>
      <xs:element name="lawyerId" type="xs:int"/>
      <xs:element name="lawyerAmount" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== Gulaev/Lawyers_Office/src/main/resources/xml_db/payment.xml
<?xml version="1.0" encoding="UTF-8"?>
<payments xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="xsd/payment.xsd">
  <payment>
    <paymentId>1</paymentId>
    <dateOfPayment>2022-01-01</dateOfPayment>
    <clientId>1</clientId>
    <lawyerId>1</lawyerId>
    <lawyerAmount>1000</lawyerAmount>
  </payment>
  <payment>
    <paymentId>2</paymentId>
    <dateOfPayment>2022-01-02</dateOfPayment>
    <clientId>1</clientId>
    <lawyerId>1</lawyerId>
    <lawyerAmount>2000</lawyerAmount>
  </payment>
  <payment>
    <paymentId>3</paymentId>
    <dateOfPayment>2022-01-03</dateOfPayment>
    <clientId>1</clientId>
    <lawyerId>1</lawyerId>
    <lawyerAmount>3000</lawyerAmount>
  </payment>
</payments>
